name: Procedural CS

on:
  schedule:
    - cron: "0 */6 * * *" 
    - cron: "0 0 * * *"   
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - run: pip install numpy

      - run: python generator.py

      - name: Commit
        run: |
          git config --global user.name "procedural-bot"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "procedural cs update $(date)" || echo "no change"
          git push